name: NetworkBanSystem
autohr: MaxCode
version: 1.0
main: me.MaxCode.NetworkBanSystem.NetworkBanSystem

commands:
     nbs:
          usage:
          default: op
     nbsui:
          usage:
          default: op